### ISSUE TITLE
Module graphs as Racket values

### ISSUE THREAD

**Issue by takikawa** [nuprl/gradual-typing-performance#121]
I propose we encode the module graphs we have as Racket values with the `graph` library and then output TikZ from that, rather than the other way around. This might be useful in doing the boundary-based prediction automation since the module graph information is needed there.

(also even better if we can build picts instead of tikz)

**Comment by bennn** [comment]
Right now, if you call `racket tools/summarize/modulegraph.rkt` with a benchmark name, it should print you a TikZ graph to the file `output.tex`. The hard part is getting the layout right -- right now, nodes are only topologically sorted.

Behind the scenes in `modulegraph.rkt`:
- `from-directory` converts a benchmark name into an adjacency list (by searching from the root of our git repo)
- `directory->tikz` turns the adj. list into `.tex`

Using the graph library would be no problem, but I don't think we gain much.

(I think we need a new library to do picts right, but that would be a good thing to have)
