### ISSUE TITLE
Don't duplicate READMEs in benchmarks

### ISSUE THREAD

**Issue by takikawa** [nuprl/gradual-typing-performance#126]
Could we set up the benchmarks so that they don't copy over README files? Maybe put the README files somewhere else?

(they take up megabytes of storage for no reason)

**Comment by bennn** [comment]
Do you mean the readmes that are generated for each benchmark (showing which modules are typed and which are untyped)? That's ok with me.

**Comment by bennn** [comment]
Should be fixed by a48a02ad92e7f1bfc70dec9644f1121d00c13b68
