### ISSUE TITLE
Lighten `benchmark-util` dependency

### ISSUE THREAD

**Issue by bennn** [nuprl/gradual-typing-performance#130]
`benchmark-util` should be removed from the benchmarks or made easier to install than `raco pkg install <repo>/tools/benchmark-util`

Ideas:
- require `benchmark-util` via path instead of collection, to make bundling easier
- put the useful essentials on `pkgs.racket-lang`
- just add a proper makefile to the top of the `gtp` repo

**Comment by bennn** [comment]
The `contract-profile` library has some code to do this. Basic idea: check if a `#%type-decl` submodule exists.

**Comment by stamourv** [comment]
Adding a makefile won't make it easier to use code out of context, which I've often found useful (i.e., when debugging contract issues).

**Comment by bennn** [comment]
Replaced the `benchmark-util` dependency with a real racket package, which should be on the package server soon. ([require-typed-check](https://github.com/bennn/require-typed-check))
